version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
      - export NVM_DIR="/root/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      - nvm install v8.10.0
      - echo 'node version'
      - node --version
      - echo 'npm version'
      - npm --version
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      # - npm test
      # Hold on integrating tests for now...
  post_build:
    commands:
      # Remove existing node_modules to clear dev dependencies
      - rm -r node_modules

      # Install runtime dependencies
      - npm install --production

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - razzle.config.js
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/*
    - node_modules/**/*
    - public/**/*
    - template-configuration.json
    - map_styles/polygon.xml
    - src/**/*
